# Generated by Django 3.2.7 on 2022-01-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GimClient',
            fields=[
                ('affiliate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('address', models.TextField(max_length=45)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('is_up_to_date', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GimRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=45)),
                ('area', models.IntegerField()),
                ('room_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GimTeacher',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone_number', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('hiring_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GimLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60)),
                ('datetime', models.DateTimeField()),
                ('price', models.IntegerField(default=2500)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gim.gimroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gim.gimteacher')),
            ],
        ),
    ]
