# Generated by Django 3.2.7 on 2022-01-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimlesson',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gim.gimteacher'),
        ),
    ]
