# Generated by Django 3.2.7 on 2021-12-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimlesson',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gim.gimroom'),
        ),
        migrations.AlterField(
            model_name='gimlesson',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
